Refine ignore terminal.
johnfrankmorgan/whitespace.nvim pull request #11
Opened 2024-07-31 04:14 UTC by Waitzz

There is a error  highlight on terminal, reproduction steps :
1. cd ~/.local/share/lazy/whitespace.nvim
2. nvim
3. :e lua/whitespace-nvim/init.lua  (in nvim's cmdline)  have a correct highlight
4. :terminal (in nivm's cmdline) have a error highlight

terminal buffer will not set fietype so the "FileType" autocmd will not be excuted , I add a "TermOpen" autocmd to clean match if "ignore_terminal" is set to true, add clean function for user can clean match if they want. and I think we should need put any conditions in hightlignt function , they should be put in function who call them.

please confirm for me , best wishes.

2024-07-31 04:18 UTC, Waitzz commented
my test nvim version infomations : nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

2024-08-08 09:05 UTC, johnfrankmorgan requested changes

2024-08-08 09:05 UTC, johnfrankmorgan commented on lua/whitespace-nvim/init.lua
> +  whitespace.highlight()
Can you use `if ... else` here like in `term_open` please? That way it's more consistent

2024-08-08 09:05 UTC, johnfrankmorgan commented on lua/whitespace-nvim/init.lua
> +whitespace.clean = function()
Maybe this could be called `nohighlight` or `remove_highlight`?

2024-08-08 09:06 UTC, johnfrankmorgan commented
Thanks for the PR @Waitzz, I've left a few comments. Let me know what you think.

2024-08-11 05:43 UTC, Waitzz commented
I have modified it according to your suggestion, please review it again, thank you ~

2024-08-18 10:52 UTC, johnfrankmorgan approved these changes

2024-08-18 10:52 UTC, merged

2024-08-18 10:52 UTC, johnfrankmorgan commented
Thanks @Waitzz!